services:
  - type: web
    name: women-safety-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false # Will be set in Render dashboard
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: SESSION_SECRET
        generateValue: true # Will generate a random value
      - key: WHATSAPP_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: GEMINI_SECRET_KEY
        sync: false